import type { Genre } from './levels'
import type { Worksheet } from './schema'

export interface Preset {
  key: string
  label: string
  sublabel: string
  genre: Genre
  levelCode: string
  worksheet: Worksheet
}

// Offline sample worksheets ported from the legacy app (no API key needed).
export const PRESETS: Preset[] = [
  {
    key: 'last-seat',
    label: '3. The Last Seat',
    sublabel: '양보와 배려 / 초등 5~6학년',
    genre: 'literature',
    levelCode: 'L3',
    worksheet: {
      index: '3',
      title: 'The Last Seat',
      vocabulary: [
        { word: 'crowded', pos: 'a.', meaning: '붐비는' },
        { word: 'passenger', pos: 'n.', meaning: '승객' },
        { word: 'elderly', pos: 'a.', meaning: '연세가 드신' },
        { word: 'hesitate', pos: 'v.', meaning: '망설이다' },
        { word: 'struggle', pos: 'v.', meaning: '애쓰다' },
        { word: 'exhausted', pos: 'a.', meaning: '기진맥진한' },
        { word: 'kindness', pos: 'n.', meaning: '친절' },
        { word: 'difference', pos: 'n.', meaning: '차이, 변화' },
      ],
      story: [
        'Emma was on her way home from school when she got on a crowded bus. It had been a long day, and she was tired. After a few minutes, a passenger left, and Emma quickly sat down in the empty seat.',
        'At the next stop, an elderly woman entered the bus. She looked tired and was carrying two heavy shopping bags. The bus was full, and there were no empty seats.',
        'Emma looked around. Several adults were sitting nearby, but nobody moved. She thought about standing up and offering her seat, but she hesitated. She was tired too, and she still had a long journey home.',
        'A few moments later, Emma noticed that the woman was struggling to keep her balance whenever the bus turned a corner. She seemed uncomfortable and exhausted.',
        'Finally, Emma stood up and offered her seat to the woman. The woman smiled warmly and thanked her. As Emma stood for the rest of the trip, she felt surprisingly happy.',
        'When Emma arrived home, she told her father what had happened. He smiled and said, "Kindness often costs very little, but it can mean a lot to someone else."',
        "That evening, Emma thought about his words. She realized that small actions can make a big difference in another person's day.",
      ],
      story_ko: [
        '에마는 학교에서 집으로 돌아가는 길에 붐비는 버스에 탔습니다. 긴 하루였고 그녀는 피곤했습니다. 몇 분 후 한 승객이 내렸고, 에마는 빈자리에 빠르게 앉았습니다.',
        '다음 정거장에서 연세가 드신 어르신 한 분이 버스에 타셨습니다. 그녀는 피곤해 보였고 무거운 쇼핑백 두 개를 들고 있었습니다. 버스는 가득 찼고 빈자리가 없었습니다.',
        '에마는 주위를 둘러보았습니다. 근처에 여러 어른들이 앉아 있었지만 아무도 움직이지 않았습니다. 그녀는 일어서서 자리를 양보할까 생각했지만 망설였습니다. 그녀 역시 피곤했고 집까지 아직 갈 길이 멀었기 때문입니다.',
        '잠시 후, 에마는 버스가 모퉁이를 돌 때마다 그 어르신이 균형을 잡으려고 애쓰는 모습을 보았습니다. 그녀는 불편하고 기진맥진해 보였습니다.',
        '결국 에마는 일어서서 어르신께 자리를 양보했습니다. 어르신은 따뜻하게 미소 지으며 고마워했습니다. 남은 여정 동안 서서 가면서도 에마는 놀랍게도 행복함을 느꼈습니다.',
        '집에 도착한 에마는 아버지께 일어난 일을 말씀드렸습니다. 아버지는 미소를 지으며 "친절은 비용이 거의 들지 않지만, 다른 사람에게는 큰 의미가 될 수 있단다."라고 말씀하셨습니다.',
        '그날 저녁, 에마는 아버지의 말씀을 깊이 생각했습니다. 그녀는 작은 행동이 다른 사람의 하루에 큰 변화를 만들 수 있다는 것을 깨달았습니다.',
      ],
      multiple_choice: [
        {
          question: 'Why was Emma tired when she got on the bus?',
          question_ko: '에마가 버스에 탔을 때 왜 피곤해했나요?',
          options: ['She ran to the bus stop.', 'She had a long day at school.', 'She was carrying heavy bags.', 'She did not sleep last night.', 'She was feeling sick.'],
          answer: 2,
          explanation: '에마는 학교에서 집으로 돌아가는 길(way home from school)이었고, 긴 하루(long day)였기 때문에 피곤했습니다.',
        },
        {
          question: 'What was the elderly woman carrying when she entered the bus?',
          question_ko: '연세가 드신 여성이 버스에 들어왔을 때 무엇을 들고 있었나요?',
          options: ['A large backpack', 'An umbrella and a wallet', 'A stroller', 'Two heavy shopping bags', 'Nothing'],
          answer: 4,
          explanation: '할머니는 무거운 쇼핑백 두 개(two heavy shopping bags)를 들고 버스에 탑승했습니다.',
        },
        {
          question: 'Why did Emma hesitate before offering her seat?',
          question_ko: '에마는 왜 자리를 양보하기 전에 망설였나요?',
          options: ['She wanted to sleep on the bus.', 'She did not see the elderly woman.', 'She was tired too and had a long journey.', 'She was waiting for someone else to stand up.', 'She did not like the elderly woman.'],
          answer: 3,
          explanation: '에마 역시 피곤했고(tired too) 집으로 가는 여정이 아직 멀었기(long journey home) 때문에 망설였습니다.',
        },
        {
          question: 'What made Emma decide to stand up?',
          question_ko: '에마가 자리를 양보하기로 결심하게 된 계기는 무엇인가요?',
          options: ['The bus driver asked her to move.', 'The woman was struggling to keep her balance.', 'Her friend told her to stand up.', 'She arrived at her stop.', 'Other passengers stared at her.'],
          answer: 2,
          explanation: '에마는 할머니가 버스가 모퉁이를 돌 때마다 중심을 잡으려고 힘겹게 버티는 모습(struggling to keep her balance)을 보고 결심했습니다.',
        },
        {
          question: 'How did Emma feel after she stood for the rest of the trip?',
          question_ko: '남은 여정 동안 서서 가면서 에마는 어떤 기분을 느꼈나요?',
          options: ['Regretful and annoyed', 'Tired and painful', 'Surprisingly happy', 'Proud and boastful', 'Dizzy and sick'],
          answer: 3,
          explanation: '서서 가면서도 에마는 의외로 행복한 기분(surprisingly happy)을 느꼈다고 기록되어 있습니다.',
        },
      ],
      subjective: [
        { question: 'What was the bus like when Emma got on?', question_ko: '에마가 탔을 때 버스의 상태는 어땠나요?', answer: 'It was crowded.' },
        { question: 'Who entered the bus at the next stop?', question_ko: '다음 정거장에서 버스에 탄 사람은 누구였나요?', answer: 'An elderly woman.' },
        { question: 'Did any of the adults sitting nearby stand up for the elderly woman?', question_ko: '근처에 앉아 있던 어른들 중 자리를 양보한 사람이 있었나요?', answer: 'No, nobody moved.' },
        { question: "What did Emma's father say about kindness?", question_ko: '에마의 아버지는 친절에 대해 뭐라고 말씀하셨나요?', answer: 'He said, "Kindness often costs very little, but it can mean a lot to someone else."' },
        { question: 'What did Emma realize that evening about small actions?', question_ko: '그날 저녁 에마는 작은 행동에 대해 무엇을 깨달았나요?', answer: "She realized that small actions can make a big difference in another person's day." },
      ],
      key_sentences: [
        { english: 'Emma was on her way home from school when she got on a crowded bus.', korean: '에마는 학교에서 집으로 돌아가는 길에 붐비는 버스에 탔습니다.' },
        { english: 'It had been a long day, and she was tired.', korean: '긴 하루였고 그녀는 피곤했습니다.' },
        { english: 'After a few minutes, a passenger left, and Emma quickly sat down in the empty seat.', korean: '몇 분 후 한 승객이 내렸고, 에마는 빈자리에 빠르게 앉았습니다.' },
        { english: 'At the next stop, an elderly woman entered the bus.', korean: '다음 정거장에서 연세가 드신 어르신 한 분이 버스에 타셨습니다.' },
        { english: 'She looked tired and was carrying two heavy shopping bags.', korean: '그녀는 피곤해 보였고 무거운 쇼핑백 두 개를 들고 있었습니다.' },
        { english: 'The bus was full, and there were no empty seats.', korean: '버스는 가득 찼고 빈자리가 없었습니다.' },
        { english: 'Emma looked around.', korean: '에마는 주위를 둘러보았습니다.' },
        { english: 'Several adults were sitting nearby, but nobody moved.', korean: '근처에 여러 어른들이 앉아 있었지만 아무도 움직이지 않았습니다.' },
        { english: 'She thought about standing up and offering her seat, but she hesitated.', korean: '그녀는 일어서서 자리를 양보할까 생각했지만 망설였습니다.' },
        { english: 'She was tired too, and she still had a long journey home.', korean: '그녀 역시 피곤했고 집까지 아직 갈 길이 멀었기 때문입니다.' },
        { english: 'A few moments later, Emma noticed that the woman was struggling to keep her balance whenever the bus turned a corner.', korean: '잠시 후, 에마는 버스가 모퉁이를 돌 때마다 그 어르신이 균형을 잡으려고 애쓰는 모습을 보았습니다.' },
        { english: 'She seemed uncomfortable and exhausted.', korean: '그녀는 불편하고 기진맥진해 보였습니다.' },
        { english: 'Finally, Emma stood up and offered her seat to the woman.', korean: '결국 에마는 일어서서 어르신께 자리를 양보했습니다.' },
        { english: 'The woman smiled warmly and thanked her.', korean: '어르신은 따뜻하게 미소 지으며 고마워했습니다.' },
        { english: 'As Emma stood for the rest of the trip, she felt surprisingly happy.', korean: '남은 여정 동안 서서 가면서도 에마는 놀랍게도 행복함을 느꼈습니다.' },
        { english: 'When Emma arrived home, she told her father what had happened.', korean: '집에 도착한 에마는 아버지께 일어난 일을 말씀드렸습니다.' },
        { english: 'He smiled and said, "Kindness often costs very little, but it can mean a lot to someone else."', korean: '아버지는 미소를 지으며 "친절은 비용이 거의 들지 않지만, 다른 사람에게는 큰 의미가 될 수 있단다."라고 말씀하셨습니다.' },
        { english: 'That evening, Emma thought about his words.', korean: '그날 저녁, 에마는 아버지의 말씀을 깊이 생각했습니다.' },
        { english: 'She realized that small actions can make a big difference in another person\'s day.', korean: '그녀는 작은 행동이 다른 사람의 하루에 큰 변화를 만들 수 있다는 것을 깨달았습니다.' },
      ],
    },
  },
  {
    key: 'little-seed',
    label: '4. The Brave Little Seed',
    sublabel: '용기와 성장 / 초등 3~4학년',
    genre: 'literature',
    levelCode: 'L2',
    worksheet: {
      index: '4',
      title: 'The Brave Little Seed',
      vocabulary: [
        { word: 'underground', pos: 'ad.', meaning: '땅속에' },
        { word: 'wonder', pos: 'v.', meaning: '궁금해하다' },
        { word: 'unknown', pos: 'n.', meaning: '미지의 세계' },
        { word: 'shiver', pos: 'v.', meaning: '몸을 떨다' },
        { word: 'stretch', pos: 'v.', meaning: '뻗다, 늘이다' },
        { word: 'surface', pos: 'n.', meaning: '표면, 지상' },
        { word: 'butterfly', pos: 'n.', meaning: '나비' },
        { word: 'courage', pos: 'n.', meaning: '용기' },
      ],
      story: [
        'Deep underground, a tiny seed named Pip lived in the dark. He was warm and safe, but he often wondered what was up above the soil. The older seeds told him stories about the bright sun and gentle rain, but Pip was afraid of the unknown.',
        'One spring morning, Pip felt a strange push from inside. The earth around him became warm, and he knew it was time to grow. "But what if the world above is too cold?" Pip whispered to himself, shivering with fear.',
        'Despite his fear, Pip took a deep breath and pushed his tiny roots downward into the cool soil. Then, he stretched his green shoot upward. He pushed and pushed, day after day, through the hard, dark dirt.',
        "Suddenly, Pip's head broke through the surface. He gasped in surprise. The world was bigger and more beautiful than he had ever imagined. The sky was bright blue, and a warm breeze shook his tiny leaves.",
        'Soon, other flowers welcomed him, and a small yellow butterfly rested on his stem. Pip was no longer a hidden seed; he was a beautiful, growing sprout. He felt proud of his journey.',
        'Pip realized that growing required a little bit of courage. If he had stayed in his warm, dark home, he would have never seen the beauty of the sun.',
      ],
      story_ko: [
        '땅속 깊은 곳에, 핍이라는 이름을 가진 작은 씨앗이 어둠 속에서 살고 있었습니다. 그는 따뜻하고 안전했지만, 종종 흙 위의 세상이 어떤지 궁금해했습니다. 나이가 더 많은 씨앗들이 그에게 밝은 태양과 부드러운 비에 대한 이야기를 들려주었지만, 핍은 미지의 세계를 두려워했습니다.',
        '어느 봄날 아침, 핍은 안에서 이상한 밀림을 느꼈습니다. 주변의 흙이 따뜻해졌고, 그는 이제 자라날 때가 되었다는 것을 알았습니다. 핍은 "하지만 위의 세상이 너무 추우면 어쩌지?"라고 혼잣말을 하며 두려움에 몸을 떨었습니다.',
        '두려움에도 불구하고, 핍은 심호흡을 하고 단단한 흙속으로 아래를 향해 작은 뿌리를 내렸습니다. 그리고 초록색 싹을 위로 뻗었습니다. 그는 매일 어둡고 단단한 흙을 뚫고 밀고 또 밀었습니다.',
        '갑자기 핍의 머리가 땅을 뚫고 표면으로 나왔습니다. 그는 놀라움에 숨을 들이켰습니다. 세상은 그가 상상했던 것보다 더 크고 아름다웠습니다. 하늘은 밝은 파란색이었고, 따뜻한 산들바람이 그의 작은 잎사귀들을 흔들었습니다.',
        '곧 다른 꽃들이 그를 환영해주었고, 작은 노란 나비 한 마리가 그의 줄기 위에서 쉬었습니다. 핍은 이제 숨겨진 씨앗이 아니라 아름답게 자라나는 새싹이었습니다. 그는 자신의 여정이 자랑스러웠습니다.',
        '핍은 성장하기 위해서는 약간의 용기가 필요하다는 것을 깨달았습니다. 만약 그가 따뜻하고 어두운 집에만 머물렀다면, 태양의 아름다움을 결코 보지 못했을 것입니다.',
      ],
      multiple_choice: [
        { question: 'Where did Pip live at the beginning of the story?', question_ko: '이야기 시작 부분에서 핍은 어디에 살고 있었나요?', options: ['On a sunny hill', 'In a greenhouse', 'Deep underground', 'In a flowerpot', 'Near a river'], answer: 3, explanation: '이야기 첫 부분에서 Pip은 땅속 깊은 곳(Deep underground)에 살고 있었다고 설명합니다.' },
        { question: 'What did the older seeds tell Pip stories about?', question_ko: '나이 든 씨앗들은 핍에게 무엇에 관한 이야기를 해주었나요?', options: ['How to hide from bugs', 'The bright sun and gentle rain', 'Stories about forest monsters', 'How to fight winter', 'The history of the soil'], answer: 2, explanation: '나이 든 씨앗들은 밝은 태양과 부드러운 비(the bright sun and gentle rain)에 관한 이야기를 들려주었습니다.' },
        { question: 'Why was Pip afraid of growing upward?', question_ko: '핍은 왜 위로 자라나는 것을 두려워했나요?', options: ['He thought the world above might be too cold.', 'He wanted to stay with his friends.', 'He did not like the sunlight.', 'He was afraid of butterflies.', 'He wanted to sleep longer.'], answer: 1, explanation: "핍은 '흙 위 세상이 너무 추우면 어쩌지?'(what if the world above is too cold?)라고 걱정했습니다." },
        { question: 'How did Pip reach the surface of the soil?', question_ko: '핍은 어떻게 흙을 뚫고 표면으로 나왔나요?', options: ['He waited for the wind to blow him.', 'A farmer dug him up.', 'He pushed roots down and stretched shoots up.', 'A butterfly pulled him out.', 'He grew sideways.'], answer: 3, explanation: '뿌리를 아래로 내리고 초록 새싹을 위로 뻗으며(roots downward... shoot upward) 성장했습니다.' },
        { question: 'What did Pip realize at the end of the story?', question_ko: '핍은 이야기의 마지막에 무엇을 깨달았나요?', options: ['Growing requires a little bit of courage.', 'It is safer to stay underground.', 'Butterflies are dangerous.', 'Spring is the coldest season.', 'Flowers are not friendly.'], answer: 1, explanation: '자라는 데에는 약간의 용기(a little bit of courage)가 필요함을 깨달았습니다.' },
      ],
      subjective: [
        { question: 'What was the name of the tiny seed?', question_ko: '작은 씨앗의 이름은 무엇이었나요?', answer: 'Pip' },
        { question: 'During which season did Pip feel a strange push from inside?', question_ko: '핍은 어느 계절에 안에서부터 이상한 밀림을 느꼈나요?', answer: 'Spring (One spring morning)' },
        { question: 'What color was the sky when Pip broke through the surface?', question_ko: '핍이 땅을 뚫고 나왔을 때 하늘은 무슨 색이었나요?', answer: 'Bright blue' },
        { question: "What insect rested on Pip's stem?", question_ko: '어떤 곤충이 핍의 줄기 위에서 쉬었나요?', answer: 'A small yellow butterfly' },
        { question: 'If Pip had stayed in his warm, dark home, what would he have never seen?', question_ko: '만약 핍이 따뜻하고 어두운 집에만 머물렀다면 무엇을 결코 보지 못했을까요?', answer: 'The beauty of the sun' },
      ],
      key_sentences: [
        { english: 'Deep underground, a tiny seed named Pip lived in the dark.', korean: '땅속 깊은 곳에, 핍이라는 이름을 가진 작은 씨앗이 어둠 속에서 살고 있었습니다.' },
        { english: 'He was warm and safe, but he often wondered what was up above the soil.', korean: '핍은 따뜻하고 안전했지만, 종종 흙 위의 세상이 어떤지 궁금해했습니다.' },
        { english: 'Pip was afraid of the unknown.', korean: '핍은 미지의 세계를 두려워했습니다.' },
        { english: 'One spring morning, Pip felt a strange push from inside.', korean: '어느 봄날 아침, 핍은 안에서부터 이상한 밀림을 느꼈습니다.' },
        { english: 'But what if the world above is too cold?', korean: '하지만 위의 세상이 너무 추우면 어쩌지?' },
        { english: 'Despite his fear, Pip took a deep breath and pushed his tiny roots downward.', korean: '두려움에도 불구하고, 핍은 심호흡을 하고 그의 작은 뿌리를 아래로 내렸습니다.' },
        { english: 'He pushed and pushed, day after day, through the hard, dark dirt.', korean: '그는 매일 어둡고 단단한 흙을 뚫고 밀고 또 밀었습니다.' },
        { english: 'The world was bigger and more beautiful than he had ever imagined.', korean: '세상은 그가 상상했던 것보다 더 크고 아름다웠습니다.' },
        { english: 'Pip realized that growing required a little bit of courage.', korean: '핍은 성장하기 위해서는 약간의 용기가 필요하다는 것을 깨달았습니다.' },
        { english: 'If he had stayed in his warm, dark home, he would have never seen the beauty of the sun.', korean: '만약 그가 따뜻하고 어두운 집에만 머물렀다면, 태양의 아름다움을 결코 보지 못했을 것입니다.' },
      ],
    },
  },
  {
    key: 'night-flight',
    label: "5. Luna's Night Flight",
    sublabel: '모험과 도전 / 초등 5~6학년',
    genre: 'literature',
    levelCode: 'L3',
    worksheet: {
      index: '5',
      title: "Luna's Night Flight",
      vocabulary: [
        { word: 'feather', pos: 'n.', meaning: '깃털' },
        { word: 'refuse', pos: 'v.', meaning: '거부하다' },
        { word: 'guide', pos: 'v.', meaning: '안내하다' },
        { word: 'shadow', pos: 'n.', meaning: '그림자' },
        { word: 'leap', pos: 'n.', meaning: '도약' },
        { word: 'gather', pos: 'v.', meaning: '모으다' },
        { word: 'glow', pos: 'v.', meaning: '빛나다' },
        { word: 'adventure', pos: 'n.', meaning: '모험' },
      ],
      story: [
        'Luna was a young owl who lived in a tall pine tree. Unlike other owls, Luna was afraid of the dark. When the sun went down, she would hide her face in her soft feathers and refuse to fly.',
        'Her mother told her, "The night holds many secrets, Luna. The stars are like small candles guiding our way." But Luna was still worried about the shadows in the forest.',
        'One evening, a strong wind blew her favorite feather out of the nest. It floated down into the deep, dark woods. Luna wanted her feather back, but the ground was covered in dark shadows.',
        'Taking courage, Luna spread her wings and took a leap into the night air. As she flew down, she realized she could see perfectly. Her large eyes gathered the light of the full moon.',
        'She scooped up her feather just before it hit the ground. When she looked up, she saw the glowing stars reflecting off the forest river. It was the most beautiful sight she had ever seen.',
        'From that night on, Luna loved the dark forest. She learned that facing her fears opened up a whole new world of adventure.',
      ],
      story_ko: [
        '루나는 키가 큰 소나무에 사는 어린 부엉이였습니다. 다른 부엉이들과 달리 루나는 어둠을 무서워했습니다. 해가 지면 루나는 부드러운 깃털 속에 얼굴을 묻고 날기를 거부했습니다.',
        '그녀의 어머니는 "루나야, 밤은 많은 비밀을 간직하고 있단다. 별들은 우리의 길을 안내하는 작은 촛불과 같아."라고 말씀하셨습니다. 하지만 루나는 여전히 숲의 그림자가 걱정되었습니다.',
        '어느 날 저녁, 강한 바람이 불어 루나가 가장 좋아하는 깃털이 둥지 밖으로 날아가 버렸습니다. 그것은 깊고 어두운 숲속으로 떠내려갔습니다. 루나는 깃털을 되찾고 싶었지만, 땅은 어두운 그림자로 덮여 있었습니다.',
        '용기를 내어 루나는 날개를 펼치고 밤공기 속으로 뛰어내렸습니다. 아래로 날아가면서 그녀는 자신이 아주 잘 볼 수 있다는 것을 깨달았습니다. 그녀의 커다란 눈이 보름달의 빛을 모아주고 있었습니다.',
        '그녀는 깃털이 땅에 닿기 직전에 그것을 낚아챘습니다. 위를 올려다보았을 때, 그녀는 숲속 강물에 반사되어 반짝이는 별들을 보았습니다. 그것은 그녀가 본 가장 아름다운 광경이었습니다.',
        '그날 밤 이후로 루나는 어두운 숲을 사랑하게 되었습니다. 그녀는 자신의 두려움에 맞서는 것이 완전히 새로운 모험의 세계를 열어준다는 것을 배웠습니다.',
      ],
      multiple_choice: [
        { question: 'Why was Luna afraid when the sun went down?', question_ko: '해가 질 때 루나는 왜 두려워했나요?', options: ['She was afraid of the pine tree.', 'She was afraid of flying in the wind.', 'She was afraid of the dark.', 'She was afraid of her mother.', 'She was afraid of the river.'], answer: 3, explanation: '루나는 다른 부엉이들과 다르게 어둠을 무서워했습니다(afraid of the dark).' },
        { question: "What did Luna's mother compare the stars to?", question_ko: '루나의 어머니는 별들을 무엇에 비유했나요?', options: ['Bright gems guiding the way', 'Small candles guiding the way', 'Glowing eyes in the forest', 'Soft feathers in the nest', 'Beautiful flowers in the woods'], answer: 2, explanation: '루나의 어머니는 별들이 우리의 길을 인도하는 작은 촛불(small candles guiding our way)과 같다고 했습니다.' },
        { question: 'What did the strong wind blow out of the nest?', question_ko: '강한 바람이 둥지 밖으로 날려 보낸 것은 무엇이었나요?', options: ["Luna's favorite feather", 'A small pine cone', 'A yellow butterfly', 'A soft green leaf', "Her mother's wing"], answer: 1, explanation: '강한 바람이 루나가 가장 좋아하는 깃털(favorite feather)을 둥지 밖으로 날려 보냈습니다.' },
        { question: 'What did Luna realize when she took a leap into the night air?', question_ko: '루나가 밤공기 속으로 뛰어내렸을 때 무엇을 깨달았나요?', options: ['She could not fly well.', 'She could see perfectly in the dark.', 'The forest was too cold.', 'She had lost her way.', 'Her mother was following her.'], answer: 2, explanation: '루나는 어둠 속으로 날아가며 자신이 완벽하게 볼 수 있다(could see perfectly)는 것을 알게 되었습니다.' },
        { question: 'What beautiful sight did Luna see reflecting off the river?', question_ko: '루나는 강물에 반사된 어떤 아름다운 광경을 보았나요?', options: ['The full moon', 'Her own reflection', 'The tall pine tree', 'The glowing stars', 'Her lost feather'], answer: 4, explanation: '루나는 숲속 강물에 반사되어 빛나는 별들(glowing stars reflecting off the forest river)을 보았습니다.' },
      ],
      subjective: [
        { question: 'Where did Luna live?', question_ko: '루나는 어디에 살았나요?', answer: 'In a tall pine tree' },
        { question: 'What did Luna refuse to do when the sun went down?', question_ko: '해가 졌을 때 루나는 무엇 하기를 거부했나요?', answer: 'To fly' },
        { question: "Where did Luna's favorite feather float down to?", question_ko: '루나가 가장 좋아하는 깃털은 어디로 떠내려갔나요?', answer: 'Into the deep, dark woods' },
        { question: 'What gathered the light of the full moon for Luna?', question_ko: '무엇이 루나를 위해 보름달의 빛을 모아주었나요?', answer: 'Her large eyes' },
        { question: 'What lesson did Luna learn from facing her fears?', question_ko: '루나는 두려움에 맞서며 어떤 교훈을 배웠나요?', answer: 'Facing her fears opened up a whole new world of adventure.' },
      ],
      key_sentences: [
        { english: 'Luna was a young owl who lived in a tall pine tree.', korean: '루나는 키가 큰 소나무에 사는 어린 부엉이였습니다.' },
        { english: 'Unlike other owls, Luna was afraid of the dark.', korean: '다른 부엉이들과 달리 루나는 어둠을 무서워했습니다.' },
        { english: 'When the sun went down, she would hide her face in her soft feathers and refuse to fly.', korean: '해가 지면 루나는 부드러운 깃털 속에 얼굴을 묻고 날기를 거부했습니다.' },
        { english: 'Her mother told her, "The night holds many secrets, Luna. The stars are like small candles guiding our way."', korean: '그녀의 어머니는 "루나야, 밤은 많은 비밀을 간직하고 있단다. 별들은 우리의 길을 안내하는 작은 촛불과 같아."라고 말씀하셨습니다.' },
        { english: 'But Luna was still worried about the shadows in the forest.', korean: '하지만 루나는 여전히 숲의 그림자가 걱정되었습니다.' },
        { english: 'One evening, a strong wind blew her favorite feather out of the nest.', korean: '어느 날 저녁, 강한 바람이 불어 루나가 가장 좋아하는 깃털이 둥지 밖으로 날아가 버렸습니다.' },
        { english: 'It floated down into the deep, dark woods.', korean: '그것은 깊고 어두운 숲속으로 떠내려갔습니다.' },
        { english: 'Luna wanted her feather back, but the ground was covered in dark shadows.', korean: '루나는 깃털을 되찾고 싶었지만, 땅은 어두운 그림자로 덮여 있었습니다.' },
        { english: 'Taking courage, Luna spread her wings and took a leap into the night air.', korean: '용기를 내어 루나는 날개를 펼치고 밤공기 속으로 뛰어내렸습니다.' },
        { english: 'As she flew down, she realized she could see perfectly.', korean: '아래로 날아가면서 그녀는 자신이 아주 잘 볼 수 있다는 것을 깨달았습니다.' },
        { english: 'Her large eyes gathered the light of the full moon.', korean: '그녀의 커다란 눈이 보름달의 빛을 모아주고 있었습니다.' },
        { english: 'She scooped up her feather just before it hit the ground.', korean: '그녀는 깃털이 땅에 닿기 직전에 그것을 낚아챘습니다.' },
        { english: 'When she looked up, she saw the glowing stars reflecting off the forest river.', korean: '위를 올려다보았을 때, 그녀는 숲속 강물에 반사되어 반짝이는 별들을 보았습니다.' },
        { english: 'It was the most beautiful sight she had ever seen.', korean: '그것은 그녀가 본 가장 아름다운 광경이었습니다.' },
        { english: 'From that night on, Luna loved the dark forest.', korean: '그날 밤 이후로 루나는 어두운 숲을 사랑하게 되었습니다.' },
        { english: 'She learned that facing her fears opened up a whole new world of adventure.', korean: '그녀는 자신의 두려움에 맞서는 것이 완전히 새로운 모험의 세계를 열어준다는 것을 배웠습니다.' },
      ],
    },
  },
]
